version: '3.8'

volumes:
  db-data: {}
  wp-data: {}
networks:
  wp-back:

services:
  db:
    container_name:  database
    image: mysql:8  
    ports:  
      - "3306:3306"
    #volumes:
    #  - ./dep/mysql:/docker-entrypoint-initdb.d
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - wp-back
    environment:  
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress



  wordpress:
    image: wordpress
    container_name: wordpress
    depends_on:
      - db
    ports:
      - "80:80"
    volumes: 
      - wp-data:/var/www/html
    restart: always
    networks:
      - wp-back
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    depends_on:
      - db
    restart: always
    ports:
      - "8080:80"
    networks:
       - wp-back
    environment:
      PMA_HOST: db
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_PASSWORD: rootPassword

